import QuerySettings from '../../../util/QuerySettings';

const sheetId = "1fwY9Ea8oQwEs5d7hIThsLf0FFOEX_g9EM7RWJLOS2fQ"; //LO Geekmo Mirror

const CharBuildSettings = new QuerySettings({
	sheetId,
	gid: 1439947023, //sheet "builds"
	headrow: 1,
	fields: {
		name: "name",
		feat_race: "feat-race",
		feat_general: "feat-general",
		feat_class: "feat-class",
		feat_skill: "feat-skill",
		feat_archetype: "feat-archetype",
		formulas: "formulas",
		languages: "languages",
		spells_0: "spells-0",
		spells_1: "spells-1",
		spells_2: "spells-2",
		spells_3: "spells-3",
		spells_4: "spells-4",
		spells_5: "spells-5",
		spells_6: "spells-6",
		spells_7: "spells-7",
		spells_8: "spells-8",
		spells_9: "spells-9",
		spells_10: "spells-10",
	},
	query: {
		colIDs: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
		colByField: {
			name: 0,
			feat_race: 1,
			feat_general: 2,
			feat_class: 3,
			feat_skill: 4,
			feat_archetype: 5,
			formulas: 6,
			languages: 7,
			spells_0: 8,
			spells_1: 9,
			spells_2: 10,
			spells_3: 11,
			spells_4: 12,
			spells_5: 13,
			spells_6: 14,
			spells_7: 15,
			spells_8: 16,
			spells_9: 17,
			spells_10: 18,
		},
		fieldByCol: {
			0: "name",
			1: "feat_race",
			2: "feat_general",
			3: "feat_class",
			4: "feat_skill",
			5: "feat_archetype",
			6: "formulas",
			7: "languages",
			8: "spells_0",
			9: "spells_1",
			10: "spells_2",
			11: "spells_3",
			12: "spells_4",
			13: "spells_5",
			14: "spells_6",
			15: "spells_7",
			16: "spells_8",
			17: "spells_9",
			18: "spells_10",
		},
		queryAll: "select A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S",
	},
	range: {
		min: 0,
		max: 18,
		str: "A2:S",
	},
});

export default CharBuildSettings;